Refactor
ambrosus/ambrosus-node pull request #432
Opened 2021-04-13 14:32 UTC by SvineruS

## Why:
* The current implementation is complex and "Spaghetti"
* Files `models/state_model.js`, `services/crypto.js`, `services/store.js`, `utils/file.js` are used only in `IdentityManager.adminAddress()` to read and write one single string to a file
* Access to `/opt` requires root permission and a `chown` cmd in travis
* `writeFile` in `utils/file.js` has a bug due to which the `/opt/hermes` folder may not be created.

## Changes:
* move `/opt/hermes/state.json` -> `./config/hermes/privateKey.txt `
* removed manipulations with `/opt/hermes` in `travis.yml`
* rename `storePath` -> `privateKeyPath` in `config/config.ts`
* merge `models/state_model.js`,
        `services/crypto.js`,
        `services/store.js`,
        `utils/file.js` into `services/private_key.js`
* `IdentityManager` receive `PrivateKey` class instead of `StateModel`
* fix hadolint DL3048 (replace `git_commit` -> `git-commit` label in Dockerfile)

# Checklist:

- [x] Code follows the style guidelines
- [ ] Documentation updated
- [ ] Corner cases evaluated and handled
- [ ] Automatic tests added/update
- [x] Automatic tests pass
- [ ] Software runs (locally or hosted)
- [x] Sanity check passed
- [x] Self-review passed

2021-04-14 03:17 UTC, seagiv approved these changes

2021-04-14 03:17 UTC, seagiv approved these changes

2021-04-14 06:15 UTC, AndrewAR2 requested changes
Все, что связано с state.json - необходимо оставить, так как это системный файл и он содержит и другую информацию, кроме приватного ключа. И не забудь восстановить его в .gitignore - мы же не хотим, чтобы приватные лючи пользователя занеслись в репозиторий.

2021-04-14 06:33 UTC, seagiv commented
> Все, что связано с state.json - необходимо оставить, так как это системный файл и он содержит и другую информацию, кроме приватного ключа. И не забудь восстановить его в .gitignore - мы же не хотим, чтобы приватные лючи пользователя занеслись в репозиторий.

Это не тот state.json, это я сделал когда-то сохранение данных в другой state.json который находится в другом каталоге, и это уже не нужно, оно не используется, а сам этот файл state.json не имеет смысла добавлять тк он не добавлен в репозиторий, он создается динамически во время инсталляции

2021-04-14 07:37 UTC, AndrewAR2 commented
> файл state.json не имеет смысла добавлять в .gitignore тк он не добавлен в репозиторий, он создается динамически во время инсталляции
Его надо добавить, так как пользователь случайно можеь его закомитить.

2021-04-28 13:57 UTC, AndrewAR2 approved these changes

2023-01-05 23:41 UTC, closed without merging